### ISSUE TITLE
Index Pattern Error

### ISSUE THREAD

**Issue by 71Imapla** [wazuh/wazuh-kibana-app#2315]
I have installed Wazuh v 3.12.3:

 cat /usr/share/kibana/plugins/wazuh/package.json | grep version
  "version": "3.12.3",
    "version": "7.7.0"

and I am using the ODFE version of the elastic search engine

API version is also 3.12.3:

"api_version":"v3.12.3"

I have oss filebeat version 7.7.1 installed:

filebeat.x86_64                          7.7.1-1                       @elasticsearch-7.x

Should filebeat version match the ODFE version ? 

![image](https://user-images.githubusercontent.com/31081438/85417601-aa5ea180-b524-11ea-9bf0-f77c05b4aa2c.png)

**Comment by jsanchez91** [comment]
Hi @71Imapla, 

This error occurs because you have not created the wazuh-alerts-3.x-* index pattern.
To check if it is created go to management -> Index Patterns.
![image](https://user-images.githubusercontent.com/3064506/85513939-cb45f600-b5fb-11ea-979c-af78ca4cf22c.png)

If you haven't created the index pattern, press the `Create Index Pattern` button, put `wazuh-alerts-3.x-*` in the entry, you should see all the indexes that match the pattern just below, if so press `Next step`
![image](https://user-images.githubusercontent.com/3064506/85515498-7acf9800-b5fd-11ea-8f0b-c12546652055.png)

In the next step, put `timestamp` in the `Time Filter field name`, click on `Show advanced options`, and put `wazuh-alerts-3.x-*` in the `Custom index pattern ID` field.

Then press the `Create index pattern` button and go to WazuhUI to check if the problem is solved.
![image](https://user-images.githubusercontent.com/3064506/85515635-a3579200-b5fd-11ea-97f3-db9b05cc87b4.png)

Let me know if your problem is solved or if you have a problem solving it.

**Comment by 71Imapla** [comment]
I had the Elasticsearch admin create those indexes -

![image](https://user-images.githubusercontent.com/31081438/85579669-eca0e500-b5ef-11ea-8455-e80ca2a0606d.png)

When I login to verify using the wazuh credentials - I do not see any index listed ( I would have thought I would at least be able to see the wazuh indexes ?) -

![image](https://user-images.githubusercontent.com/31081438/85579931-25d95500-b5f0-11ea-8dbe-a7c1b90d4a33.png)

**Comment by jsanchez91** [comment]
Hi @71Imapla,

This happens because you have enabled the tenants, we fixed it in v3.13.0-7.7.0.

The saved object of the index pattern is located in the user's private tenant, you must create a new index pattern with your wazuh user.

**Comment by 71Imapla** [comment]
Sounds like I should also upgrade. I will try this solution today, and let you know.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 71Imapla** [comment]
We don't have any tenants set up outside of the default 'global'. I am able to run a curl command with the wazuh credentials  - which shows the template exists.  Are there some docs or references we can check regarding how the the wazuh user is supposed to be setup ?   We are trying to limit permissions of wazuh to what is needed only.  For example we do not want the wazuh user to be able to do anything outside of what we need it to do.  

I will still plan on the updated from Wazuh 3.12.3 to 3.13 today while we wait your reply.

**Comment by 71Imapla** [comment]
Update completed:

```
 cat /usr/share/kibana/plugins/wazuh/package.json | grep version
  "version": "3.13.0",
    "version": "7.7.0"
```

wazuh-manager and API:
```
 rpm -qa | grep wazuh
wazuh-api-3.13.0-1.x86_64
wazuh-manager-3.13.0-1.x86_64
```
wazuh-manager-3.13.0-1.x86_64

**Comment by jsanchez91** [comment]
Hi @71Imapla,

Has the problem with the index pattern been solved by updating?

As for your question about Wazuh's permits, we are working on updating our documentation.

Here are the steps to set up the permissions:

### 1. Create a role for the `kibanaserver` user.
The WazuhUI uses the `kibanaserver` user for some tasks, you need to grant permissions to this user to read and write the Wazuh indexes.
Go to the Opendistro Security plugin in Kibana and create a new role called "wazuh_ui". In the index permissions tab add new index permissions like this screenshot.

![image](https://user-images.githubusercontent.com/3064506/85990354-2b6cdb80-b9f2-11ea-9c4d-71fa454c141f.png)

Then click on the "Save role definition" button and go to "Role mapping". In the role mapping view press the "+" button and add the following settings.

![image](https://user-images.githubusercontent.com/3064506/85991342-979c0f00-b9f3-11ea-852b-8d5fbf3cf216.png)

### 2. Create a role to use WazuhUI
Go to the Opendistro Security plugin in Kibana and create a new role called "wazuh_user". In the index permissions tab add new index permissions like this screenshot.
![image](https://user-images.githubusercontent.com/3064506/85992487-40973980-b9f5-11ea-871c-ec34da04299d.png)

After saving, go to "Internal user database" and add a new user. In this example I called the user "wazuh_user", write the password and add the roles "kibana_user" and "wazuh_user".
![image](https://user-images.githubusercontent.com/3064506/85992991-f3679780-b9f5-11ea-856a-30186e85c236.png)

You can now access Kibana with the wazuh_user, and it only has permissions in the Wazuh indexes.

**Comment by 71Imapla** [comment]
Update to the latest version did not help. We are working through these instructions and will let you know if that helps

**Comment by 71Imapla** [comment]
Sorry for the delay in my response.  However, we are still getting the error: 

![image](https://user-images.githubusercontent.com/31081438/86599988-42608000-bf54-11ea-991a-baa3ef7903f1.png)

I updated /etc/filebeat/wazuh-template.json to match the username / password combination for the new wazuh user / role we created to test this.

**Comment by 71Imapla** [comment]
I followed your earlier suggestion on creating the index pattern.  I can now happily report that I all looks well now:
![image](https://user-images.githubusercontent.com/31081438/86603966-9ae64c00-bf59-11ea-8c86-fdbaf16de1d2.png)

**Comment by jsanchez91** [comment]
I'm glad I could help you, if everything is resolved I'll close the Issue.

If you have any further questions, please do not hesitate to reopen the Issue or use our [slack channel](https://wazuh.com/community/join-us-on-slack/), our [Google group](https://groups.google.com/forum/#!forum/wazuh)

Regards, 
Jose
