### ISSUE TITLE
Plugin installation failure - 403

### ISSUE THREAD

**Issue by cnicolov** [wazuh/wazuh-kibana-app#9]
Hi when I try to install the Wazuh Kibana app from the provided URL the response is 403

**Comment by snaow** [comment]
Hi @cnicolov,

You were right, we had some issues with the S3 distribution bucket. Could you try again? It should be fixed now.

Thanks for the feedback, we really appreciate it.

**Comment by yanyov** [comment]
Hi,

The url from the stable branch still don't work. 
When i try to install the plugin I get: 
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/http://wazuh.com/resources/wazuh-app.zip/http://wazuh.com/resources/wazuh-app.zip-5.0.2.zip

Plugin installation was unsuccessful due to error "No valid url specified.

**Comment by snaow** [comment]
Hi @yanyov,

Please use "master" branch instead, we currently does not have a stable version (we will release it in few days), that branch was out of date, sorry for the confusion.

Use master branch, installing the App with URL:

``/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.0_5.2.2.zip``

Regards,
Pedro 'snaow' Sanchez.
